http {
    upstream demo_pool {
        policy round_robin;
        server backend-1:80;
        server backend-2:80;
    }

    server {
        listen 8080 default_server;
        server_name localhost;

        location / {
            headers {
                response_add X-Upstream-Pool demo_pool;
                response_add X-Proxy ngxora;
            }
            proxy_pass http://demo_pool;
        }
    }
}
